# fly.toml app configuration file generated for live-streaming-server on 2025-03-14T00:22:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'live-streaming-server'
primary_region = 'otp'

[build]

[env]
  PORT = '3000'

[[mounts]]
  source = 'live_stream_data'
  destination = '/app/hls'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
